
name: Serve2025
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup
        run: |
          Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip
          .\ngrok\ngrok.exe authtoken 2hbZgX1CpuKEHsG4muxj6FF5EQL_7onmAtgmeQKL5jagXJuPR
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          set-localuser -Name "Administrator" -Password ("Admin@2025" | ConvertTo-SecureString -AsPlainText -Force)
          Start-Process .\ngrok\ngrok.exe -ArgumentList "tcp --region ap 3389"
          sleep 21600
